fixtures:
  repositories:
    stdlib: "git://github.com/puppetlabs/puppetlabs-stdlib.git"
    eyplib: "git://github.com/SaltaIT/eyp-eyplib.git"
    concat: "git://github.com/puppetlabs/puppetlabs-concat.git"
  symlinks:
    multipathd: "#{source_dir}"
